/*
 * Generated by TASKING Pin Mapper Tool for AURIX
 * - device  : TC23x
 * - package : TQFP100
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>

#include <_Reg/IfxCan_bf.h>
#include <_Reg/IfxCan_reg.h>
#include <_Reg/IfxQspi_bf.h>
#include <_Reg/IfxQspi_reg.h>
#include <_Reg/IfxScu_bf.h>
#include <_Reg/IfxScu_reg.h>
#include <_Reg/IfxVadc_bf.h>
#include <_Reg/IfxVadc_reg.h>


/* iLLD driver modules */

#define IFXCFG_MODULE_IFX_MULTICAN0
#define IFXCFG_MODULE_IFX_QSPI1
#define IFXCFG_MODULE_IFX_SCU0
#define IFXCFG_MODULE_IFX_VADC0


/* iLLD peripheral driver I/O connections */

// can0_node1
#define IFXCFG_MULTICAN0_1_RXD                  IfxMultican_RXD1B_P14_1_IN
#define IFXCFG_MULTICAN0_1_RXD_MODE             IfxPort_InputMode_noPullDevice
#define IFXCFG_MULTICAN0_1_RXD_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed1
#define IFXCFG_MULTICAN0_1_TXD                  IfxMultican_TXD1_P14_0_OUT
#define IFXCFG_MULTICAN0_1_TXD_MODE             IfxPort_OutputMode_pushPull
#define IFXCFG_MULTICAN0_1_TXD_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed4

// evr1v
#define IFXCFG_SCU0_MODE                        IfxScu_HWCFG0DCLDO_P14_6_IN
#define IFXCFG_SCU0_MODE_MODE                   IfxPort_InputMode_pullUp
#define IFXCFG_SCU0_MODE_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed1

// qspi1_m
#define IFXCFG_QSPI1_MRST                       IfxQspi1_MRSTB_P11_3_IN
#define IFXCFG_QSPI1_MRST_MODE                  IfxPort_InputMode_noPullDevice
#define IFXCFG_QSPI1_MRST_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1
#define IFXCFG_QSPI1_MTSR                       IfxQspi1_MTSR_P11_9_OUT
#define IFXCFG_QSPI1_MTSR_MODE                  IfxPort_OutputMode_pushPull
#define IFXCFG_QSPI1_MTSR_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4
#define IFXCFG_QSPI1_SCLK                       IfxQspi1_SCLK_P11_6_OUT
#define IFXCFG_QSPI1_SCLK_MODE                  IfxPort_OutputMode_pushPull
#define IFXCFG_QSPI1_SCLK_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4
#define IFXCFG_QSPI1_SLSO3                      IfxQspi1_SLSO3_P11_10_OUT
#define IFXCFG_QSPI1_SLSO3_MODE                 IfxPort_OutputMode_pushPull
#define IFXCFG_QSPI1_SLSO3_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed4

// scu
#define IFXCFG_SCU0_HWCFG3                      IfxScu_HWCFG3_P14_3_IN
#define IFXCFG_SCU0_HWCFG3_MODE                 IfxPort_InputMode_pullUp
#define IFXCFG_SCU0_HWCFG3_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed1
#define IFXCFG_SCU0_HWCFG4                      IfxScu_HWCFG4_P10_5_IN
#define IFXCFG_SCU0_HWCFG4_MODE                 IfxPort_InputMode_noPullDevice
#define IFXCFG_SCU0_HWCFG4_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed1
#define IFXCFG_SCU0_HWCFG5                      IfxScu_HWCFG5_P10_6_IN
#define IFXCFG_SCU0_HWCFG5_MODE                 IfxPort_InputMode_noPullDevice
#define IFXCFG_SCU0_HWCFG5_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed1


/* Symbolic names for GPIO ports */

// p00_0
#define IFXCFG_PORT_GPIO1                       IfxPort_P00_0
#define IFXCFG_PORT_GPIO1_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO1_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_4
#define IFXCFG_PORT_GPIO4                       IfxPort_P02_4
#define IFXCFG_PORT_GPIO4_MODE                  IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_GPIO4_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1

// p02_5
#define IFXCFG_PORT_GPIO5                       IfxPort_P02_5
#define IFXCFG_PORT_GPIO5_MODE                  IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_GPIO5_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1

// p02_6
#define IFXCFG_PORT_GPIO7                       IfxPort_P02_6
#define IFXCFG_PORT_GPIO7_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO7_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_7
#define IFXCFG_PORT_GPIO8                       IfxPort_P02_7
#define IFXCFG_PORT_GPIO8_MODE                  IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_GPIO8_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1

// p11_8
#define IFXCFG_PORT_GPIO9                       IfxPort_P11_8
#define IFXCFG_PORT_GPIO9_MODE                  IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_GPIO9_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1

// p11_11
#define IFXCFG_PORT_GPIO11                      IfxPort_P11_11
#define IFXCFG_PORT_GPIO11_MODE                 IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO11_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed4

// p11_12
#define IFXCFG_PORT_GPIO12                      IfxPort_P11_12
#define IFXCFG_PORT_GPIO12_MODE                 IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO12_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_0
#define IFXCFG_PORT_MCU_DCDC_EN_2               IfxPort_P13_0
#define IFXCFG_PORT_MCU_DCDC_EN_2_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_DCDC_EN_2_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_1
#define IFXCFG_PORT_MCU_DCDC_EN_3               IfxPort_P13_1
#define IFXCFG_PORT_MCU_DCDC_EN_3_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_DCDC_EN_3_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_2
#define IFXCFG_PORT_MCU_DCDC_EN_4               IfxPort_P13_2
#define IFXCFG_PORT_MCU_DCDC_EN_4_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_DCDC_EN_4_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p13_3
#define IFXCFG_PORT_MCU_SOC_PWERBTN             IfxPort_P13_3
#define IFXCFG_PORT_MCU_SOC_PWERBTN_MODE        IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SOC_PWERBTN_PAD_DRIVER  IfxPort_PadDriver_cmosAutomotiveSpeed4

// p14_4
#define IFXCFG_PORT_GPIO6                       IfxPort_P14_4
#define IFXCFG_PORT_GPIO6_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO6_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_0
#define IFXCFG_PORT_GPIO3                       IfxPort_P15_0
#define IFXCFG_PORT_GPIO3_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO3_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_5
#define IFXCFG_PORT_GPIO10                      IfxPort_P15_5
#define IFXCFG_PORT_GPIO10_MODE                 IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_GPIO10_PAD_DRIVER           IfxPort_PadDriver_cmosAutomotiveSpeed1

// p20_8
#define IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT      IfxPort_P20_8
#define IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT_MODE IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed1

// p21_4
#define IFXCFG_PORT_GPIO2                       IfxPort_P21_4
#define IFXCFG_PORT_GPIO2_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO2_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p21_6
#define IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK    IfxPort_P21_6
#define IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK_MODE IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed1

// p33_5
#define IFXCFG_PORT_MCU_5VCAP_FET_EN            IfxPort_P33_5
#define IFXCFG_PORT_MCU_5VCAP_FET_EN_MODE       IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_5VCAP_FET_EN_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_6
#define IFXCFG_PORT_MCU_DCDC_EN                 IfxPort_P33_6
#define IFXCFG_PORT_MCU_DCDC_EN_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_DCDC_EN_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_7
#define IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON       IfxPort_P33_7
#define IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON_MODE  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_8
#define IFXCFG_PORT_MCU_SOC_RESET               IfxPort_P33_8
#define IFXCFG_PORT_MCU_SOC_RESET_MODE          IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_MCU_SOC_RESET_PAD_DRIVER    IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_10
#define IFXCFG_PORT_SOC_MCU_RSMRST_B            IfxPort_P33_10
#define IFXCFG_PORT_SOC_MCU_RSMRST_B_MODE       IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_SOC_MCU_RSMRST_B_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed1


/* Generic port I/O configuration */

#define IFXCFG_P00_0_IO_CONFIG                  { &IFXCFG_PORT_GPIO1, IFXCFG_PORT_GPIO1_MODE, IFXCFG_PORT_GPIO1_PAD_DRIVER }
#define IFXCFG_P02_4_IO_CONFIG                  { &IFXCFG_PORT_GPIO4, IFXCFG_PORT_GPIO4_MODE, IFXCFG_PORT_GPIO4_PAD_DRIVER }
#define IFXCFG_P02_5_IO_CONFIG                  { &IFXCFG_PORT_GPIO5, IFXCFG_PORT_GPIO5_MODE, IFXCFG_PORT_GPIO5_PAD_DRIVER }
#define IFXCFG_P02_6_IO_CONFIG                  { &IFXCFG_PORT_GPIO7, IFXCFG_PORT_GPIO7_MODE, IFXCFG_PORT_GPIO7_PAD_DRIVER }
#define IFXCFG_P02_7_IO_CONFIG                  { &IFXCFG_PORT_GPIO8, IFXCFG_PORT_GPIO8_MODE, IFXCFG_PORT_GPIO8_PAD_DRIVER }
#define IFXCFG_P11_8_IO_CONFIG                  { &IFXCFG_PORT_GPIO9, IFXCFG_PORT_GPIO9_MODE, IFXCFG_PORT_GPIO9_PAD_DRIVER }
#define IFXCFG_P11_11_IO_CONFIG                 { &IFXCFG_PORT_GPIO11, IFXCFG_PORT_GPIO11_MODE, IFXCFG_PORT_GPIO11_PAD_DRIVER }
#define IFXCFG_P11_12_IO_CONFIG                 { &IFXCFG_PORT_GPIO12, IFXCFG_PORT_GPIO12_MODE, IFXCFG_PORT_GPIO12_PAD_DRIVER }
#define IFXCFG_P13_0_IO_CONFIG                  { &IFXCFG_PORT_MCU_DCDC_EN_2, IFXCFG_PORT_MCU_DCDC_EN_2_MODE, IFXCFG_PORT_MCU_DCDC_EN_2_PAD_DRIVER }
#define IFXCFG_P13_1_IO_CONFIG                  { &IFXCFG_PORT_MCU_DCDC_EN_3, IFXCFG_PORT_MCU_DCDC_EN_3_MODE, IFXCFG_PORT_MCU_DCDC_EN_3_PAD_DRIVER }
#define IFXCFG_P13_2_IO_CONFIG                  { &IFXCFG_PORT_MCU_DCDC_EN_4, IFXCFG_PORT_MCU_DCDC_EN_4_MODE, IFXCFG_PORT_MCU_DCDC_EN_4_PAD_DRIVER }
#define IFXCFG_P13_3_IO_CONFIG                  { &IFXCFG_PORT_MCU_SOC_PWERBTN, IFXCFG_PORT_MCU_SOC_PWERBTN_MODE, IFXCFG_PORT_MCU_SOC_PWERBTN_PAD_DRIVER }
#define IFXCFG_P14_4_IO_CONFIG                  { &IFXCFG_PORT_GPIO6, IFXCFG_PORT_GPIO6_MODE, IFXCFG_PORT_GPIO6_PAD_DRIVER }
#define IFXCFG_P15_0_IO_CONFIG                  { &IFXCFG_PORT_GPIO3, IFXCFG_PORT_GPIO3_MODE, IFXCFG_PORT_GPIO3_PAD_DRIVER }
#define IFXCFG_P15_5_IO_CONFIG                  { &IFXCFG_PORT_GPIO10, IFXCFG_PORT_GPIO10_MODE, IFXCFG_PORT_GPIO10_PAD_DRIVER }
#define IFXCFG_P20_8_IO_CONFIG                  { &IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT, IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT_MODE, IFXCFG_PORT_SOC_PMIC_MCU_STARTBOOT_PAD_DRIVER }
#define IFXCFG_P21_4_IO_CONFIG                  { &IFXCFG_PORT_GPIO2, IFXCFG_PORT_GPIO2_MODE, IFXCFG_PORT_GPIO2_PAD_DRIVER }
#define IFXCFG_P21_6_IO_CONFIG                  { &IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK, IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK_MODE, IFXCFG_PORT_SOC_PMIC_MCU_SUSPWRDNACK_PAD_DRIVER }
#define IFXCFG_P33_5_IO_CONFIG                  { &IFXCFG_PORT_MCU_5VCAP_FET_EN, IFXCFG_PORT_MCU_5VCAP_FET_EN_MODE, IFXCFG_PORT_MCU_5VCAP_FET_EN_PAD_DRIVER }
#define IFXCFG_P33_6_IO_CONFIG                  { &IFXCFG_PORT_MCU_DCDC_EN, IFXCFG_PORT_MCU_DCDC_EN_MODE, IFXCFG_PORT_MCU_DCDC_EN_PAD_DRIVER }
#define IFXCFG_P33_7_IO_CONFIG                  { &IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON, IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON_MODE, IFXCFG_PORT_MCU_SOC_PMIC_POWER_ON_PAD_DRIVER }
#define IFXCFG_P33_8_IO_CONFIG                  { &IFXCFG_PORT_MCU_SOC_RESET, IFXCFG_PORT_MCU_SOC_RESET_MODE, IFXCFG_PORT_MCU_SOC_RESET_PAD_DRIVER }
#define IFXCFG_P33_10_IO_CONFIG                 { &IFXCFG_PORT_SOC_MCU_RSMRST_B, IFXCFG_PORT_SOC_MCU_RSMRST_B_MODE, IFXCFG_PORT_SOC_MCU_RSMRST_B_PAD_DRIVER }


/* Initialization routines */

extern void gpio_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
