/*
 * Generated by TASKING Pin Mapper Tool for AURIX
 * - device  : TC23x
 * - package : TQFP100
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P02_4_IO_CONFIG,
    IFXCFG_P02_5_IO_CONFIG,
    IFXCFG_P02_6_IO_CONFIG,
    IFXCFG_P02_7_IO_CONFIG,
    IFXCFG_P11_8_IO_CONFIG,
    IFXCFG_P11_11_IO_CONFIG,
    IFXCFG_P11_12_IO_CONFIG,
    IFXCFG_P13_0_IO_CONFIG,
    IFXCFG_P13_1_IO_CONFIG,
    IFXCFG_P13_2_IO_CONFIG,
    IFXCFG_P13_3_IO_CONFIG,
    IFXCFG_P14_4_IO_CONFIG,
    IFXCFG_P15_0_IO_CONFIG,
    IFXCFG_P15_5_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG,
    IFXCFG_P21_4_IO_CONFIG,
    IFXCFG_P21_6_IO_CONFIG,
    IFXCFG_P33_5_IO_CONFIG,
    IFXCFG_P33_6_IO_CONFIG,
    IFXCFG_P33_7_IO_CONFIG,
    IFXCFG_P33_8_IO_CONFIG,
    IFXCFG_P33_10_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}

